### PR TITLE
use ocean instead of global pes in MOM_oda_driver

### PR DESCRIPTION
**Pull request by feiyulu**

### CODE REVIEW

**Review by MJHarrison-GFDL — COMMENTED** [review]
We need to put the references to eakf_oda_mod and ensemble_filter in cpp blocks since there are currently no publicly available interfaces

**Comment by feiyulu** [comment]
I started a pull request to add a dummy eakf_oda_mod into MOM6_DA_hooks. Do you think that will work?

**Comment by MJHarrison-GFDL** [comment]
I think it is better for now to encapsulate in cpp directives. We can discuss at the meeting on the general topic of interfaces for MOM6

**Comment by feiyulu** [comment]
Cpp directives? I'm not familiar with it. I'll revert those relevant lines back and only merge the other modifications.

**Comment by MJHarrison-GFDL** [comment]
You can wrab the lines in 

#ifdef ENABLE_ECDA
..
#

As a follow-up comment. I am opposed to  making eakf a generic interface since it is refers to our filter implementation.

**Comment by feiyulu** [comment]
Yes, that makes sense. EAKF shouldn't be part of the interface.

**Pull request merged**
